suite docker-compose

diff --git a/Docker-compose/app-web-node/Dockerfile b/Docker-compose/app-web-node/Dockerfile
--- a/Docker-compose/app-web-node/Dockerfile
+++ b/Docker-compose/app-web-node/Dockerfile
@@ -9,6 +9,10 @@ COPY index.js .
 
 RUN npm install 
 
+RUN apk add curl
+
 EXPOSE 3000
+
+# HEALTHCHECK --interval=1m --timeout=30s --retries=3 CMD curl --fail http://localhost:3000 || exit 1
 
 CMD ["node", "index.js"]
